server:
  port: 0
  servlet:
    context-path: /context
spring:
  application:
    name: dbagent-api
  credentials:
    config:
      password: ftp_client
      username: ftp_client
      hostname: serverdevops.abexa.pe
      port: 1003
      connection-timeout: 5000
  transmitter:
    config:
      shared-directory: /home/jenkins/DockerProjects/samba-dockerproject/shared
      username-db: beex-payment-webapi
      password-db: beex-payment-webapi
      hostname-db: 192.168.1.11
      port-db: 1433
      file-size: 100M
      file-limit: 100
      database-name: AGPS_Pruebas
  receiver:
    config:
      shared-directory: /home/serverdev/Documents/DockerProjects/ftp-docker-project/data
      mssql-external-directory: /mnt/virtual_machines/SQL
      mssql-internal-directory: /var/opt/mssql/data
      username-db: yorklin
      password-db: 123
      hostname-db: 192.168.1.2
      port-db: 1434
      database-name: BdGestionActividad
  flow-mode: 'receiver'  # 'receiver', 'transmitter'
